
version: "3.9"

services:
  myproj123:
    image: registry.gitlab.com/houssemneji29/myproj123/myproj123-${deployment_environment}:${tag}
    container_name: myproj123-${deployment_environment}
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${external_port}:3000"
